=== ARVIPE/Ejercicios-Programaci-n/Repositorio personal LMSGI/practicasparaexamen/clientesempresaelectrica.dtd
<!ELEMENT empresa (clientes+,facturas*, metododepago,socios)>
<!ELEMENT clientes (cliente*,socio1?)*>
<!ELEMENT facturas (moroso1?,moroso2)>
<!ATTLIST empresa nombre CDATA #FIXED "Endesa">
<!ELEMENT cliente EMPTY>
<!ENTITY % datosclientes "nombre ID #IMPLIED
                          DNI IDREF #REQUIRED
                          edad IDREFS #REQUIRED">
<!ATTLIST cliente %datosclientes;>
<!ELEMENT moroso1 EMPTY>
<!ATTLIST moroso1 pago CDATA #REQUIRED>
<!ELEMENT moroso2 EMPTY>
<!ATTLIST moroso2 pago CDATA #IMPLIED>
<!ELEMENT metododepago (cliente1*)>
<!ELEMENT cliente1 (#PCDATA|efectivo|tarjeta)*>
<!ELEMENT efectivo EMPTY>
<!ELEMENT tarjeta EMPTY>
<!ELEMENT socios (socio1)>
<!ELEMENT socio1 EMPTY>
<!ATTLIST socio1 desde (2015|2016|2017|2018) #REQUIRED>
<!ENTITY corte "electricidad">

=== ARVIPE/Ejercicios-Programaci-n/Repositorio personal LMSGI/practicasparaexamen/clientesempresaelectrica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "clientesempresaelectrica.dtd">

<empresa nombre ="Endesa">

    <clientes> No hay &electricidad desde hace 3 días;

        <cliente nombre ="Alberto Catetas"   DNI ="M23490987"  edad = "34 años"/>
        <cliente nombre ="Paca Garte"        DNI ="Q42823246"  edad = "42 años"/>    
        <cliente nombre="Ana Bohueles"       DNI ="P32829245"  edad = "54 años"/>

    </clientes>

    <facturas>
    
        <moroso1 pago ="500 lereles"/>
        <moroso2 pago ="330 lereles"/>
    
    </facturas>

    <metododepago>

        <cliente1><efectivo/></cliente1>


    </metododepago>

    <socios>

        <socio1 desde ="2015"/>

    </socios>



</empresa>
