=== ARVIPE/Ejercicios-Programaci-n/Repositorio personal LMSGI/xml y dtd/Losvengadores.dtd
<!ELEMENT UniversoMarvel (superheroes?, superheroe?, supervillanos?, supervillano?, peliculas?, pelicula?)*>
<!ELEMENT superheroes (superheroe+)>
<!ELEMENT superheroe EMPTY>
<!ELEMENT supervillanos (supervillano+)>
<!ELEMENT supervillano EMPTY>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula EMPTY>
<!ENTITY % caracteristicas "nombre CDATA #REQUIRED
                            superpoder CDATA #REQUIRED">
<!ATTLIST superheroe %caracteristicas;>
<!ENTITY % caracteristicassv "nombre CDATA #REQUIRED   
                              superpoder CDATA #REQUIRED">
<!ATTLIST supervillano %caracteristicassv;>
<!ENTITY % tipopeliculas "nombre CDATA #REQUIRED
                          aÃ±o CDATA #REQUIRED">
<!ATTLIST pelicula %tipopeliculas;>

=== ARVIPE/Ejercicios-Programaci-n/Repositorio personal LMSGI/xml y dtd/LosVengadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE UniversoMarvel SYSTEM "Losvengadores.dtd">

<UniversoMarvel>

    <superheroes>
        <superheroe nombre = "Iron Man" superpoder = "Tener oroh"/>
        <superheroe nombre = "Thor" superpoder = "Fuerza"/>
        <superheroe nombre = "Capitan América" superpoder = "Ta mazao"/>
    </superheroes>
    <supervillanos>
        <supervillano nombre = "Thanos" superpoder = "Guantalete del infinito"/>
        <supervillano nombre = "Loki" superpoder = "Al final se hace bueno pero se lo cargan"/>
    </supervillanos>
    <peliculas>
        <pelicula nombre = "Infinity War" año = "2018"/>
        <pelicula nombre = "End Game" año = "2019" />
    </peliculas>

</UniversoMarvel>
